name: Publish to Zapier
on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3

      - name: Install Deps
        run: yarn install

      - name: Compile TypeScript
        run: yarn build

      - name: Zapier Validate
        env:
          ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_API_KEY }}
        run: yarn zapier validate

      - name: Push to Zapier
        env:
          ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_API_KEY }}
        run: yarn zapier push
