name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  zapier-validations:
    runs-on: ubuntu-latest
    name: Zapier Validations
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.3.0

      - name: Install Node Modules
        run: yarn install

      - name: Compile TypeScript
        run: yarn build

      - name: Zapier Validate
        env:
          ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_API_KEY }}
        run: yarn zapier validate
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.3.0

      - name: Install Node Modules
        run: yarn install

      - name: Lint
        run: yarn run lint:ts
  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.3.0

      - name: Install Node Modules
        run: yarn install

      - name: Lint
        run: yarn run typecheck
